name: ASP.NET Deploy

on:
  push:
    tags:
      - 'dev-*'
      - 'test-*'
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore ClinicalResearchApp/ClinicalResearchApp.csproj

      - name: Build project
        run: dotnet build ClinicalResearchApp/ClinicalResearchApp.csproj --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish ClinicalResearchApp/ClinicalResearchApp.csproj --configuration Release --output ./publish --no-build

      - name: Zip publish output
        run: Compress-Archive -Path ./publish/* -DestinationPath ./publish.zip
        shell: pwsh

  deploy-dev:
    needs: build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/dev-')
    steps:
      - name: Download code
        uses: actions/checkout@v3

      - name: Copy to DEVELOPMENT IIS directory (SMB)
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./publish.zip
          remote: '${{ secrets.DEV_IIS_PATH }}/publish.zip'
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          password: ${{ secrets.DEV_PASSWORD }}

  deploy-test:
    needs: build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/test-')
    steps:
      - name: Download code
        uses: actions/checkout@v3

      - name: Copy to TEST IIS directory (SMB)
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./publish.zip
          remote: '${{ secrets.TEST_IIS_PATH }}/publish.zip'
          host: ${{ secrets.TEST_HOST }}
          username: ${{ secrets.TEST_USERNAME }}
          password: ${{ secrets.TEST_PASSWORD }}

  deploy-prod:
    needs: build
    runs-on: windows-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download code
        uses: actions/checkout@v3

      - name: Copy to PRODUCTION IIS directory (SMB)
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./publish.zip
          remote: '${{ secrets.PROD_IIS_PATH }}/publish.zip'
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          password: ${{ secrets.PROD_PASSWORD }}
