name: ASP.NET Deploy

on:
  push:
    tags:
      - 'dev-*'
      - 'test-*'
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.300'

      - name: Restore dependencies
        run: dotnet restore ClinicalResearchApp.csproj --runtime win-x64

      - name: Build project
        run: dotnet build ClinicalResearchApp.csproj --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish ClinicalResearchApp.csproj --configuration Release --runtime win-x64 --output ./publish --no-build

      - name: Zip publish output
        run: Compress-Archive -Path ./publish/* -DestinationPath ./publish.zip
        shell: pwsh

  deploy-dev:
    needs: build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/dev-')
    steps:
      - name: Download code
        uses: actions/checkout@v3

      - name: Copy to DEVELOPMENT IIS directory (SMB)
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./publish.zip
          remote: '${{ secrets.DEV_IIS_PATH }}/publish.zip'
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          password: Inh@le&Exh@le24